Draft: Slack host request
29ki/29k pull request #748
Opened 2022-10-24 14:23 UTC by swemail

To create a workflow where we can interact with request for public host roles via slack

2022-10-25 11:12 UTC, gewfy requested changes

2022-10-25 11:12 UTC, gewfy commented on functions/src/api/index.ts
> +const slackIntegrationRouter = cerateSlackRouter();
"cereate"

2022-10-25 11:40 UTC, swemail commented on functions/package.json
> +    "start": "yarn build && firebase emulators:start --project demo-29k-cupcake --import emulatorSeed",
No oops here, one way of having valid accounts I thought. But we can script em up instead 😄

2022-10-25 18:05 UTC, gewfy requested changes
Nice work! Some minor changes :)

2022-10-25 18:05 UTC, gewfy commented on functions/src/lib/slack.ts
> +    SLACK_PUBLIC_HOST_REQUESTS_CHANNEL &&
I was more thinking that we should use `SLACK_PUBLIC_HOST_REQUESTS_CHANNEL` to determine if we should send the message. That way we can have some messages being sent, and some not. Checking for `SLACK_BOT_NAME`, `SLACK_OAUTH_TOKEN` here makes total sense thought!

2022-10-25 18:10 UTC, gewfy requested changes
Oh one more thing, could we name the slack channels `#app-host-requests` and `#app-host-requests-staging` so they are grouped with the rest of the `#app-` channels?

2022-10-26 05:30 UTC, swemail commented on functions/jest.setup.js
> +};
The SO way I'm afraid, but works

2022-10-26 11:25 UTC, gewfy approved these changes
Mer eller mindre superbt!

2022-10-26 11:27 UTC, merged